-- MySQL Script generated by MySQL Workbench
-- dom 26 mai 2019 13:08:52 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema smallgroups
-- -----------------------------------------------------
-- Banco de dados do sistema de celulas
DROP SCHEMA IF EXISTS `smallgroups` ;

-- -----------------------------------------------------
-- Schema smallgroups
--
-- Banco de dados do sistema de celulas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smallgroups` DEFAULT CHARACTER SET utf8 ;
USE `smallgroups` ;

-- -----------------------------------------------------
-- Table `smallgroups`.`profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smallgroups`.`profile` ;

CREATE TABLE IF NOT EXISTS `smallgroups`.`profile` (
  `oid_profile` VARCHAR(36) NOT NULL,
  `nm_profile` VARCHAR(45) NOT NULL,
  `des_profile` VARCHAR(45) NULL,
  PRIMARY KEY (`oid_profile`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smallgroups`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smallgroups`.`users` ;

CREATE TABLE IF NOT EXISTS `smallgroups`.`users` (
  `oid_users` VARCHAR(36) NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `bol_active` TINYINT(1) NOT NULL DEFAULT 1,
  `remember_token` VARCHAR(100) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NOT NULL,
  `profile_oid_profile` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`oid_users`, `profile_oid_profile`),
  UNIQUE INDEX `des_user_UNIQUE` (`name` ASC),
  INDEX `fk_users_profile1_idx` (`profile_oid_profile` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `fk_users_profile1`
    FOREIGN KEY (`profile_oid_profile`)
    REFERENCES `smallgroups`.`profile` (`oid_profile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smallgroups`.`addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smallgroups`.`addresses` ;

CREATE TABLE IF NOT EXISTS `smallgroups`.`addresses` (
  `oid_addresses` VARCHAR(36) NOT NULL,
  `street` VARCHAR(60) NOT NULL,
  `number` INT(11) NOT NULL,
  `neiborhood` VARCHAR(60) NOT NULL,
  `city` VARCHAR(60) NOT NULL,
  `state` VARCHAR(60) NOT NULL,
  `cep` CHAR(8) NULL,
  PRIMARY KEY (`oid_addresses`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smallgroups`.`people`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smallgroups`.`people` ;

CREATE TABLE IF NOT EXISTS `smallgroups`.`people` (
  `oid_people` VARCHAR(36) NOT NULL,
  `nm_people` VARCHAR(60) NOT NULL,
  `birthday` DATE NULL,
  `phone` VARCHAR(45) NULL,
  `cellphone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `users_oid_users` VARCHAR(36) NOT NULL,
  `addresses_oid_addresses` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`oid_people`),
  INDEX `fk_people_users_idx` (`users_oid_users` ASC),
  INDEX `fk_people_addresses1_idx` (`addresses_oid_addresses` ASC),
  CONSTRAINT `fk_people_users`
    FOREIGN KEY (`users_oid_users`)
    REFERENCES `smallgroups`.`users` (`oid_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_people_addresses1`
    FOREIGN KEY (`addresses_oid_addresses`)
    REFERENCES `smallgroups`.`addresses` (`oid_addresses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smallgroups`.`small_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smallgroups`.`small_groups` ;

CREATE TABLE IF NOT EXISTS `smallgroups`.`small_groups` (
  `oid_small_groups` VARCHAR(36) NOT NULL,
  `des_small_groups` VARCHAR(60) NOT NULL,
  `bol_active` TINYINT(1) NOT NULL DEFAULT 1,
  `addresses_oid_addresses` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`oid_small_groups`),
  INDEX `fk_small_groups_addresses1_idx` (`addresses_oid_addresses` ASC),
  CONSTRAINT `fk_small_groups_addresses1`
    FOREIGN KEY (`addresses_oid_addresses`)
    REFERENCES `smallgroups`.`addresses` (`oid_addresses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smallgroups`.`peoplexsmallgruops`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smallgroups`.`peoplexsmallgruops` ;

CREATE TABLE IF NOT EXISTS `smallgroups`.`peoplexsmallgruops` (
  `oid_peoplexsmallgruops` VARCHAR(36) NOT NULL,
  `bol_active` TINYINT(1) NOT NULL DEFAULT 1,
  `people_oid_people` VARCHAR(36) NOT NULL,
  `small_groups_oid_small_groups` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`oid_peoplexsmallgruops`),
  INDEX `fk_peoplexsmallgruops_people1_idx` (`people_oid_people` ASC),
  INDEX `fk_peoplexsmallgruops_small_groups1_idx` (`small_groups_oid_small_groups` ASC),
  CONSTRAINT `fk_peoplexsmallgruops_people1`
    FOREIGN KEY (`people_oid_people`)
    REFERENCES `smallgroups`.`people` (`oid_people`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_peoplexsmallgruops_small_groups1`
    FOREIGN KEY (`small_groups_oid_small_groups`)
    REFERENCES `smallgroups`.`small_groups` (`oid_small_groups`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smallgroups`.`ministrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smallgroups`.`ministrations` ;

CREATE TABLE IF NOT EXISTS `smallgroups`.`ministrations` (
  `oid_ministrations` VARCHAR(36) NOT NULL,
  `nm_ministration` VARCHAR(45) NOT NULL,
  `des_ministration` VARCHAR(100) NOT NULL,
  `attachment` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`oid_ministrations`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smallgroups`.`ministrationsxusers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smallgroups`.`ministrationsxusers` ;

CREATE TABLE IF NOT EXISTS `smallgroups`.`ministrationsxusers` (
  `oid_ministrationsxusers` VARCHAR(36) NOT NULL,
  `ministrations_oid_ministrations` VARCHAR(36) NOT NULL,
  `users_oid_users` VARCHAR(36) NOT NULL,
  `bol_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`oid_ministrationsxusers`),
  INDEX `fk_ministrations_has_users_users1_idx` (`users_oid_users` ASC),
  INDEX `fk_ministrations_has_users_ministrations1_idx` (`ministrations_oid_ministrations` ASC),
  CONSTRAINT `fk_ministrations_has_users_ministrations1`
    FOREIGN KEY (`ministrations_oid_ministrations`)
    REFERENCES `smallgroups`.`ministrations` (`oid_ministrations`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ministrations_has_users_users1`
    FOREIGN KEY (`users_oid_users`)
    REFERENCES `smallgroups`.`users` (`oid_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smallgroups`.`attachment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smallgroups`.`attachment` ;

CREATE TABLE IF NOT EXISTS `smallgroups`.`attachment` (
  `oid_attachment` VARCHAR(36) NOT NULL,
  `path` VARCHAR(45) NOT NULL,
  `ministrations_oid_ministrations` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`oid_attachment`),
  INDEX `fk_attachment_ministrations1_idx` (`ministrations_oid_ministrations` ASC),
  CONSTRAINT `fk_attachment_ministrations1`
    FOREIGN KEY (`ministrations_oid_ministrations`)
    REFERENCES `smallgroups`.`ministrations` (`oid_ministrations`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smallgroups`.`messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smallgroups`.`messages` ;

CREATE TABLE IF NOT EXISTS `smallgroups`.`messages` (
  `oid_messages` INT NOT NULL,
  `nm_message` VARCHAR(45) NULL,
  `des_message` VARCHAR(45) NULL,
  PRIMARY KEY (`oid_messages`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smallgroups`.`messagesxusers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smallgroups`.`messagesxusers` ;

CREATE TABLE IF NOT EXISTS `smallgroups`.`messagesxusers` (
  `oid_messagesxusers` VARCHAR(36) NOT NULL,
  `bol_active` TINYINT(1) NOT NULL DEFAULT 1,
  `messages_oid_messages` INT NOT NULL,
  `users_oid_users` VARCHAR(36) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`oid_messagesxusers`),
  INDEX `fk_messages_has_users_users1_idx` (`users_oid_users` ASC),
  INDEX `fk_messages_has_users_messages1_idx` (`messages_oid_messages` ASC),
  CONSTRAINT `fk_messages_has_users_messages1`
    FOREIGN KEY (`messages_oid_messages`)
    REFERENCES `smallgroups`.`messages` (`oid_messages`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_messages_has_users_users1`
    FOREIGN KEY (`users_oid_users`)
    REFERENCES `smallgroups`.`users` (`oid_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
